server:
  port: 8090
  forward-headers-strategy: framework

spring:
  application:
    name: userManager
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_CLIENT_REDIRECT}
            scope:
              - email
              - profile

  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: admin
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties.hibernate.format_sql: true